# Generated by Django 2.0.6 on 2021-09-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('pk_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('imagen1', models.URLField(default='https://i.pinimg.com/736x/3a/ab/e0/3aabe0e9a520b9ad90407a82f85adb42.jpg', max_length=800)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['nombre'],
            },
        ),
    ]
